name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Set this to your Node.js version

      - name: Install dependencies
        run: npm install  # or use yarn

      - name: Run tests
        run: npm test  # Adjust this to your test script

      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}  # Vercel token stored in GitHub secrets
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  # Vercel Org ID stored in GitHub secrets
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}  # Vercel Project ID stored in GitHub secrets
          alias-domains: 'your-domain.com'  # Optional: Set this to your custom domain if configured
