version: 2
updates:
  - package-ecosystem: "npm"  # or "yarn" if you are using Yarn
    directory: "/"  # Location of package.json in the repository
    schedule:
      interval: "weekly"  # How often to check for updates
    open-pull-requests-limit: 5  # Maximum number of open pull requests
