name: Generate Release Notes

on:
  push:
    tags:
      - 'v*'  # This workflow triggers on push events to tags like v1.0, v1.1, etc.

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify your Node.js version

      - name: Install GitHub Release Notes (gren)
        run: npm install -g github-release-notes

      - name: Generate Release Notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gren release --tags=all --override
