apiVersion: v1
kind: Service
metadata:
  name: heavens-above-service
spec:
  selector:
    app: heavens-above
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
