name: Deploy Documentation

on:
  push:
    branches:
      - main  # Trigger the workflow on push events to the main branch.
    paths:
      - 'docs/**'  # Only trigger when documentation files are changed.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python  # Only necessary for MkDocs
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies  # Only necessary for MkDocs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build documentation  # Adjust command for Jekyll if needed
        run: mkdocs build  # Use 'jekyll build' for Jekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site  # For MkDocs, use './_site' for Jekyll
